<?php

namespace app\modules\admin\controllers;

use zbsoft\base\Controller;

/**
 * Base controller for the `admin` module
 */
class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        
    }
}
