<?php

namespace app\modules\admin\controllers;

use app\models\Admin;
use zbsoft\base\Controller;

/**
 * Base controller for the `admin` module
 */
class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(!Admin::isLogin()){
            $this->redirect("admin/public/login");
        }
    }
}
