<?php

namespace app\modules\admin\controllers;

use app\models\Admin;
use zbsoft\base\Controller;
use Zb;
use zbsoft\base\Response;
use zbsoft\exception\NotFoundHttpException;
use zbsoft\helpers\Json;

/**
 * Base controller for the `admin` module
 */
class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!Admin::isLogin()) {
            if (Zb::$app->request->isAjax) {
                exit(json_encode(["flag" => false, "msg" => "请先登录"]));
            } else {
                $this->redirect("/admin/public/login");
            }
        }
    }

    /**
     * 登出
     * @return array
     * @throws NotFoundHttpException
     */
    public function actionLogout()
    {
        if (Zb::$app->request->isPost) {
            return Json::encode(["flag" => Admin::logout()]);
        } else {
            Zb::$app->response->statusCode = 404;
            throw new NotFoundHttpException(Response::$httpStatuses[404]);
        }
    }
}
