<?php

namespace app\controllers;
use app\models\Config;
use zbsoft\base\Controller;

/**
 * Base controller for the `admin` module
 */
class BaseController extends Controller
{
    public $sysConfig;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->sysConfig = Config::getAllByCache();
    }
}