<?php
/**
 * @link https://github.com/JohnZhang360/Simple-Yii2.git
 */

namespace app\controllers;

use zbsoft\base\Controller;

class SearchController extends Controller
{
    public function init()
    {
        $this->layout = false;

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render("index");
    }
}