<?php
/**
 * @link https://github.com/JohnZhang360/Simple-Yii2.git
 */

namespace app\controllers;

use app\models\Search;
use zbsoft\base\Controller;

class SearchController extends Controller
{
    public function init()
    {
        $this->layout = false;

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchList = Search::find()->orderBy("sort asc, created_at asc")->all();
        return $this->render("index", ['searchList'=>$searchList]);
    }
}